### ISSUE TITLE
Serverless Test returns non-zero code

### ISSUE THREAD

**Issue by sean9keenan** [sean9keenan/serverless-go-build#2]

**Comment by mblarsen** [comment]
Any plans of implementing "test" :)

> Coming soon ...

**Comment by sean9keenan** [comment]
Hehe - there is some test functionality, just not the ability for it to run a specific test outside of running _all_ of the specified tests. Documentation is a little bit lacking, but you can see in the readme there is a `tests` key, if you specify test files to run it should run them when you run `serverless test`

**Comment by mblarsen** [comment]
Cool, will give it a try
